apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-init
  labels:
    app: store
spec:
  template:
    spec:
      containers:
      - name: cluster-init
        image: cockroachdb/cockroach:v2.1.1
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "init"
          - "--insecure"
          - "--host=store-0.store"
      restartPolicy: OnFailure
